name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  solution: ./TestApp/TestApp.sln
  packageDir: ./TestApp/pkgs

jobs:
  build:
    env:
      buildVersion: '5.2.${{github.run_number}}'
      nugetAuthToken: ${{ secrets.NuGetAPIKey }}
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Print Variables
      run: echo $buildVersion
    - name: Restore Dependencies
      run: dotnet restore $solution
    - name: Build for Test
      run: dotnet build --no-restore --version-suffix $buildVersion $solution
    - name: Test
      run: dotnet test --no-build --verbosity normal $solution
    - name: Build for Release
      run: dotnet build --no-restore -c Release --version-suffix $buildVersion $solution
    - name: Package Assemblies
      run: dotnet pack --no-build $solution -p:PackageVersion=$buildVersion -o $packageDir q
    - name: Push Packages to Repository
      run: dotnet nuget push -s https://api.nuget.org/v3/index.json -k $nugetAuthToken $packageDir/*.nupkg
